# Generated by Django 5.2.6 on 2025-09-11 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=500)),
                ('sites', models.JSONField()),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='backend_sea_created_816a54_idx'), models.Index(fields=['status'], name='backend_sea_status_627fc5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('base_url', models.URLField()),
                ('search_path', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='backend_sit_name_afef8d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('image_url', models.URLField()),
                ('product_url', models.URLField()),
                ('site', models.CharField(max_length=50)),
                ('confidence', models.FloatField(default=1.0)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='backend.search')),
            ],
            options={
                'indexes': [models.Index(fields=['search'], name='backend_pro_search__cfeaf7_idx'), models.Index(fields=['site'], name='backend_pro_site_23e594_idx')],
            },
        ),
    ]
