# Generated by Django 5.2.6 on 2025-09-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='reviews_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='backend_pro_price_6ea8fc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['rating'], name='backend_pro_rating_9e4340_idx'),
        ),
    ]
