# Generated by Django 5.2.6 on 2025-09-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_product_rating_product_reviews_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
